applicationname: Kraken
applicationversion:  v0.0.1
timeformat: 2006-01-02T15:04:05Z07:00
host: localhost
port: 8000
defaultstore: ./
filesuffix: .kraken
autoWriteinterval: 10s
strictslashesinurls: true
outputformat: JSON 