applicationname: Kraken
applicationversion:  v0.0.1
timeformat: 2001-01-01T13:01:01Z02:00
host: localhost
port: 8000
defaultstore: ./
filesuffix: .kraken
autowriteinterval: 10s
strictslashesinurls: true
outputformat: JSON 